/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xmlprojectvf;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rsyntaxtextarea.SyntaxScheme;
import org.fife.ui.rsyntaxtextarea.TokenMakerFactory;
import org.fife.ui.rtextarea.RTextScrollPane;
import org.jdom2.Attribute;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;
/**
 *
 * @author anase
 */
public class frame extends javax.swing.JFrame {
    
    /**
     * Creates new form frame
     */
    public frame() {
        
        artistes = new ArrayList<Artiste>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        btnAbout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnXML = new javax.swing.JButton();
        btnShowT = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        pHome = new javax.swing.JPanel();
        pCode = new javax.swing.JPanel();
        pShow = new javax.swing.JPanel();
        pAdd = new javax.swing.JPanel();
        pAbout = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        xmlPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tabPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableR = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        addPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_titre_film = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_genre_film = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_pays_film = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_annee_film = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tf_nom_role = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_prenom_role = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_intitule_role = new javax.swing.JTextField();
        btn_ajouter_role = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_resume_film = new javax.swing.JTextArea();
        btn_ajouter_filme = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        aboutPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1180, 664));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1160, 664));

        navPanel.setBackground(new java.awt.Color(255, 255, 255));
        navPanel.setMinimumSize(new java.awt.Dimension(219, 663));
        navPanel.setPreferredSize(new java.awt.Dimension(219, 663));
        navPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbout.setBackground(new java.awt.Color(255, 255, 255));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8-haute-importance-32.png"))); // NOI18N
        btnAbout.setText("       Info");
        btnAbout.setBorderPainted(false);
        btnAbout.setContentAreaFilled(false);
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.setEnabled(false);
        btnAbout.setFocusPainted(false);
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbout.setOpaque(true);
        btnAbout.setPreferredSize(new java.awt.Dimension(187, 37));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        navPanel.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoHB.png"))); // NOI18N
        btnHome.setText("       Accueil");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);
        btnHome.setFocusable(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setOpaque(true);
        btnHome.setPreferredSize(new java.awt.Dimension(187, 37));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        navPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        btnXML.setBackground(new java.awt.Color(255, 255, 255));
        btnXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoXMLB.png"))); // NOI18N
        btnXML.setText("       Afficher (XML)");
        btnXML.setBorderPainted(false);
        btnXML.setContentAreaFilled(false);
        btnXML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXML.setFocusPainted(false);
        btnXML.setFocusable(false);
        btnXML.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXML.setOpaque(true);
        btnXML.setPreferredSize(new java.awt.Dimension(187, 37));
        btnXML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXMLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXMLMouseExited(evt);
            }
        });
        btnXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXMLActionPerformed(evt);
            }
        });
        navPanel.add(btnXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btnShowT.setBackground(new java.awt.Color(255, 255, 255));
        btnShowT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoRechB.png"))); // NOI18N
        btnShowT.setText("       Rechercher");
        btnShowT.setBorderPainted(false);
        btnShowT.setContentAreaFilled(false);
        btnShowT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowT.setFocusPainted(false);
        btnShowT.setFocusable(false);
        btnShowT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnShowT.setOpaque(true);
        btnShowT.setPreferredSize(new java.awt.Dimension(187, 37));
        btnShowT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShowTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShowTMouseExited(evt);
            }
        });
        btnShowT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTActionPerformed(evt);
            }
        });
        navPanel.add(btnShowT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoAddB.png"))); // NOI18N
        btnAdd.setText("       Ajouter");
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdd.setOpaque(true);
        btnAdd.setPreferredSize(new java.awt.Dimension(187, 37));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        navPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        pHome.setBackground(new java.awt.Color(243, 167, 1));
        pHome.setMaximumSize(new java.awt.Dimension(7, 37));
        pHome.setMinimumSize(new java.awt.Dimension(7, 37));
        pHome.setPreferredSize(new java.awt.Dimension(7, 37));
        pHome.setVisible(true);

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        navPanel.add(pHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        pCode.setBackground(new java.awt.Color(243, 167, 1));
        pCode.setMaximumSize(new java.awt.Dimension(7, 37));
        pCode.setMinimumSize(new java.awt.Dimension(7, 37));
        pCode.setVisible(false);

        javax.swing.GroupLayout pCodeLayout = new javax.swing.GroupLayout(pCode);
        pCode.setLayout(pCodeLayout);
        pCodeLayout.setHorizontalGroup(
            pCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pCodeLayout.setVerticalGroup(
            pCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        navPanel.add(pCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        pShow.setBackground(new java.awt.Color(243, 167, 1));
        pShow.setMaximumSize(new java.awt.Dimension(7, 37));
        pShow.setMinimumSize(new java.awt.Dimension(7, 37));
        pShow.setVisible(false);

        javax.swing.GroupLayout pShowLayout = new javax.swing.GroupLayout(pShow);
        pShow.setLayout(pShowLayout);
        pShowLayout.setHorizontalGroup(
            pShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pShowLayout.setVerticalGroup(
            pShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        navPanel.add(pShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        pAdd.setBackground(new java.awt.Color(243, 167, 1));
        pAdd.setMaximumSize(new java.awt.Dimension(7, 37));
        pAdd.setMinimumSize(new java.awt.Dimension(7, 37));
        pAdd.setVisible(false);

        javax.swing.GroupLayout pAddLayout = new javax.swing.GroupLayout(pAdd);
        pAdd.setLayout(pAddLayout);
        pAddLayout.setHorizontalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pAddLayout.setVerticalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        navPanel.add(pAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        pAbout.setBackground(new java.awt.Color(243, 167, 1));
        pAbout.setMaximumSize(new java.awt.Dimension(7, 37));
        pAbout.setMinimumSize(new java.awt.Dimension(7, 37));
        pAbout.setVisible(false);

        javax.swing.GroupLayout pAboutLayout = new javax.swing.GroupLayout(pAbout);
        pAbout.setLayout(pAboutLayout);
        pAboutLayout.setHorizontalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        pAboutLayout.setVerticalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        navPanel.add(pAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/epolyLogo.jpg"))); // NOI18N
        navPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 70));

        jLabel18.setText("EL MRABTI Anas");
        navPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, -1, -1));

        topPanel.setBackground(new java.awt.Color(243, 167, 1));
        topPanel.setMinimumSize(new java.awt.Dimension(957, 35));
        topPanel.setPreferredSize(new java.awt.Dimension(957, 37));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8-menu-31.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8-effacer-30.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setBackground(new java.awt.Color(34, 91, 137));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ouvrir ");
        jLabel13.setOpaque(true);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8-ouvrir-le-document-100.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8-sauvegarder-100.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setEnabled(false);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(34, 91, 137));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Enregistrer");
        jLabel15.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(536, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jPanel1.add(homePanel, "card2");

        xmlPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout xmlPanelLayout = new javax.swing.GroupLayout(xmlPanel);
        xmlPanel.setLayout(xmlPanelLayout);
        xmlPanelLayout.setHorizontalGroup(
            xmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xmlPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        xmlPanelLayout.setVerticalGroup(
            xmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xmlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        textArea = new RSyntaxTextArea(20, 60);
        AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory)TokenMakerFactory.getDefaultInstance();
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_XML);
        textArea.setCodeFoldingEnabled(true);
        SyntaxScheme esquema = textArea.getSyntaxScheme();
        //esquema.getStyle(Token.LITERAL_NUMBER_DECIMAL_INT).foreground = Color.black;
        //esquema.getStyle(Token.RESERVED_WORD).foreground = Color.blue;
        // Code of sub-components and layout - not shown here
        RTextScrollPane sp = new RTextScrollPane(textArea);
        jPanel2.add(sp);

        jPanel1.add(xmlPanel, "card2");

        tabPanel.setBackground(new java.awt.Color(255, 255, 255));
        tabPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(Color.white);

        jTableR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Genre", "Pays", "Année", "Mes", "Roles", "Resume", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableR.setRowHeight(25);
        jTableR.getColumnModel().getColumn(5).setMinWidth(0);
        jTableR.getColumnModel().getColumn(5).setMaxWidth(0);
        jTableR.getColumnModel().getColumn(7).setMinWidth(20);
        jTableR.getColumnModel().getColumn(7).setMaxWidth(20);
        jTableR.getColumnModel().getColumn(5).setWidth(0);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTableR.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        jTableR.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        jTableR.getColumnModel().getColumn(2).setPreferredWidth(8);
        jTableR.getColumnModel().getColumn(3).setPreferredWidth(8);
        jTableR.getColumnModel().getColumn(4).setPreferredWidth(5);
        jTableR.getModel().addTableModelListener(
            new TableModelListener(){
                public void tableChanged(TableModelEvent e){
                    jLabel16.setEnabled(true);
                }
            }
        );
        jTableR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableR);

        tabPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 960, 540));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Recherche");
        tabPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        tabPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 210, -1));

        jPanel1.add(tabPanel, "card2");

        addPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(0, 4, 20, 5));

        jLabel4.setText("Titre");
        jPanel3.add(jLabel4);

        tf_titre_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_titre_filmActionPerformed(evt);
            }
        });
        jPanel3.add(tf_titre_film);

        jLabel5.setText("Genre");
        jPanel3.add(jLabel5);
        jPanel3.add(tf_genre_film);

        jLabel6.setText("Pays");
        jPanel3.add(jLabel6);
        jPanel3.add(tf_pays_film);

        jLabel7.setText("Année");
        jPanel3.add(jLabel7);
        jPanel3.add(tf_annee_film);

        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("<html><u>Metteur en scène</u></html>");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8);

        jComboBox1.setRequestFocusEnabled(false);
        jComboBox1.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jComboBox1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 1, 10, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(0, 2, 15, 8));

        jLabel9.setText("Nom");
        jPanel5.add(jLabel9);
        jPanel5.add(tf_nom_role);

        jLabel10.setText("Prénom");
        jPanel5.add(jLabel10);
        jPanel5.add(tf_prenom_role);

        jLabel11.setText("Intitule");
        jPanel5.add(jLabel11);
        jPanel5.add(tf_intitule_role);

        btn_ajouter_role.setText("<html><u>Ajouter</u></html>");
        btn_ajouter_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouter_roleActionPerformed(evt);
            }
        });
        btn_ajouter_role.setBorderPainted(false);

        btn_ajouter_role.setContentAreaFilled(false);

        btn_ajouter_role.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_ajouter_role.setFocusPainted(false);

        btn_ajouter_role.setFocusable(false);
        jPanel5.add(btn_ajouter_role);

        jPanel4.add(jPanel5);

        jScrollPane2.getViewport().setBackground(Color.white);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Intitule"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2);

        jLabel12.setText("Resumé");

        ta_resume_film.setColumns(20);
        ta_resume_film.setRows(5);
        jScrollPane3.setViewportView(ta_resume_film);

        btn_ajouter_filme.setText("Ajouter");
        btn_ajouter_filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouter_filmeActionPerformed(evt);
            }
        });

        jButton1.setText("Vider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(btn_ajouter_filme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ajouter_filme)
                    .addComponent(jButton1))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Ajouter des Roles"));

        jPanel1.add(addPanel, "card2");

        aboutPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jPanel1.add(aboutPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearForm(){
        tf_annee_film.setText("");
        tf_genre_film.setText("");
        tf_intitule_role.setText("");
        tf_nom_role.setText("");
        tf_pays_film.setText("");
        tf_titre_film.setText("");
        tf_prenom_role.setText("");
        ta_resume_film.setText("");
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
    }
    private void readFilmFile(String file){
        artistes.clear();
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableR.getModel();
        defaultTableModel.setRowCount(0);
        SAXBuilder builder = new SAXBuilder();
        File xmlFile = new File(file);
        try {
            Document document = (Document) builder.build(xmlFile);
            Element rootNode = document.getRootElement();
            List list = rootNode.getChildren("FILM");
            List listArtiste = rootNode.getChildren("ARTISTE");
            for(int i = 0; i < list.size(); i++){
                Element node = (Element) list.get(i);
                Element nodeMES = node.getChild("MES");
                Film filme = new Film(node.getChildText("TITRE"),
                        node.getChildText("GENRE"),
                        node.getChildText("PAYS"),
                        Integer.valueOf(node.getAttributeValue("Annee")),
                        Integer.valueOf(nodeMES.getAttributeValue("idref")),
                        node.getChildText("RESUME")
                );
                Element nodeRoles = (Element) node.getChild("ROLES");
                List roles =  nodeRoles.getChildren("ROLE");
                for(int j = 0; j < roles.size(); j++){
                    Element roleElement = (Element) roles.get(j);
                    role r = new role(
                            roleElement.getChildText("NOM"),
                            roleElement.getChildText("PRENOM"),
                            roleElement.getChildText("INTITULE")
                    );
                    filme.roles.add(r);
                }
                DefaultTableModel tblModel = (DefaultTableModel) jTableR.getModel();
                Object data[]  = {filme.getTitre(),filme.getGenre(), filme.getPays(),filme.getAnnee(),filme.getMes(),filme.getRoles(), filme.getResume()};
                tblModel.addRow(data);
                jTableR.getColumnModel().getColumn(7).setCellRenderer(new Renderer());
            }
            for(int i = 0; i < listArtiste.size() ; i++){
                Element node = (Element) listArtiste.get(i);
                jComboBox1.addItem(node.getAttributeValue("id"));
                artistes.add(new Artiste(
                        Integer.valueOf(node.getAttributeValue("id")),
                        node.getChildText("ACTNOM"),
                        node.getChildText("ACTPNOM"),
                        node.getChildText("ANNEENAISS"))
                );
            }

        } catch (JDOMException ex) {
            Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void toForm(){
        DefaultTableModel model = (DefaultTableModel) jTableR.getModel();
        int i = jTableR.getSelectedRow();
        tf_titre_film.setText(model.getValueAt(i, 0).toString());
        tf_genre_film.setText(model.getValueAt(i, 1).toString());
        tf_pays_film.setText(model.getValueAt(i, 2).toString());
        tf_annee_film.setText(model.getValueAt(i, 3).toString());
        jComboBox1.setSelectedItem(model.getValueAt(i, 4).toString());
        if(model.getValueAt(i, 6) != null)
        ta_resume_film.setText(model.getValueAt(i, 6).toString());
        ArrayList<role> roles = (ArrayList<role>) model.getValueAt(i,5);
       DefaultTableModel mdl = (DefaultTableModel) jTable1.getModel();
       mdl.setRowCount(0);
        for (int j = 0; j < roles.size(); j++){
            role r = roles.get(j);
            Object data[]  = {r.getNom(), r.getPrenom(), r.getIntitule()};
            mdl.addRow(data);
        }
        pHome.setVisible(false);
        pShow.setVisible(false);
        pCode.setVisible(false);
        pAdd.setVisible(true);
        pAbout.setVisible(false);
        homePanel.setVisible(false);
        xmlPanel.setVisible(false);
        tabPanel.setVisible(false);
        addPanel.setVisible(true);
        aboutPanel.setVisible(false);
    }
    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        /*
        btnAbout.setBackground(new Color(243,167,1));
        btnAbout.setForeground(Color.WHITE);
        */
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        /*
        btnAbout.setBackground(Color.WHITE);
        btnAbout.setForeground(Color.BLACK);
        */
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setBackground(new Color(243,167,1));
        btnHome.setForeground(Color.WHITE);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoHW.png"))); 
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setBackground(Color.WHITE);
        btnHome.setForeground(Color.BLACK);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoHB.png"))); 
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnXMLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMLMouseEntered
        btnXML.setBackground(new Color(243,167,1));
        btnXML.setForeground(Color.WHITE);
        btnXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoXMLW.png")));
    }//GEN-LAST:event_btnXMLMouseEntered

    private void btnXMLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMLMouseExited
        btnXML.setBackground(Color.WHITE);
        btnXML.setForeground(Color.BLACK);
        btnXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoXMLB.png")));
    }//GEN-LAST:event_btnXMLMouseExited

    private void btnShowTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowTMouseEntered
        btnShowT.setBackground(new Color(243,167,1));
        btnShowT.setForeground(Color.WHITE);
        btnShowT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoRechW.png")));
    }//GEN-LAST:event_btnShowTMouseEntered

    private void btnShowTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowTMouseExited
        btnShowT.setBackground(Color.WHITE);
        btnShowT.setForeground(Color.BLACK);
        btnShowT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoRechB.png")));
    }//GEN-LAST:event_btnShowTMouseExited

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBackground(new Color(243,167,1));
        btnAdd.setForeground(Color.WHITE);
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoAddW.png")));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setBackground(Color.WHITE);
        btnAdd.setForeground(Color.BLACK);
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icoAddB.png")));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        //allWhite();
        btnHome.setBackground(new Color(243,167,1));
        homePanel.setVisible(true);
        xmlPanel.setVisible(false);
        tabPanel.setVisible(false);
        addPanel.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnXMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMLMouseClicked
        homePanel.setVisible(false);
        xmlPanel.setVisible(true);
        tabPanel.setVisible(false);
        addPanel.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_btnXMLMouseClicked

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        pHome.setVisible(true);
        pShow.setVisible(false);
        pCode.setVisible(false);
        pAdd.setVisible(false);
        pAbout.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXMLActionPerformed
        // TODO add your handling code here:*pHome.setVisible(true);
        pHome.setVisible(false);
        pShow.setVisible(false);
        pCode.setVisible(true);
        pAdd.setVisible(false);
        pAbout.setVisible(false);
    }//GEN-LAST:event_btnXMLActionPerformed

    private void btnShowTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTActionPerformed
        // TODO add your handling code here:
        pHome.setVisible(false);
        pShow.setVisible(true);
        pCode.setVisible(false);
        pAdd.setVisible(false);
        pAbout.setVisible(false);
        homePanel.setVisible(false);
        xmlPanel.setVisible(false);
        tabPanel.setVisible(true);
        addPanel.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_btnShowTActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        pHome.setVisible(false);
        pShow.setVisible(false);
        pCode.setVisible(false);
        pAdd.setVisible(true);
        pAbout.setVisible(false);
        homePanel.setVisible(false);
        xmlPanel.setVisible(false);
        tabPanel.setVisible(false);
        addPanel.setVisible(true);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        pHome.setVisible(false);
        pShow.setVisible(false);
        pCode.setVisible(false);
        pAdd.setVisible(false);
        pAbout.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        /*if(navPanel.getBounds().width >= 200){
            navPanel.setBounds(0, 0, 72, 663);
        }*/
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tf_titre_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_titre_filmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_titre_filmActionPerformed

    private void jTableRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRMouseClicked
    if(evt.getClickCount()==2){
        toForm();
    }
    else{
        if(evt.getClickCount()==1){
        int row = jTableR.rowAtPoint(evt.getPoint());
        int col = jTableR.columnAtPoint(evt.getPoint());
        if(row >= 0 && col == 7){
            /***************************************************************************/
            DefaultTableModel model = (DefaultTableModel) jTableR.getModel();
            int selectedRow = jTableR.getSelectedRow();
            ArrayList<role> roles = (ArrayList<role>) model.getValueAt(selectedRow,5);
            JTable mytable = new JTable();
                mytable.setBackground(Color.WHITE);
                mytable.setOpaque(true);
                
                mytable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Nom", "Prénom", "Intitule"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.String.class, java.lang.String.class
                    };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            DefaultTableModel mdl = (DefaultTableModel) mytable.getModel();
                    for (int i = 0; i < roles.size(); i++){
                        role r = roles.get(i);
                        Object data[]  = {r.getNom(), r.getPrenom(), r.getIntitule()};
                        mdl.addRow(data);
                    }
            JScrollPane scrollPane = new  JScrollPane(mytable);
            scrollPane.setBackground(Color.WHITE);
            scrollPane.setOpaque(true);
            JFrame f = new JFrame();
            f.setTitle("Roles");
            f.getContentPane().add(scrollPane,BorderLayout.CENTER);
            f.setSize(400,150);
            f.setBackground(Color.WHITE);
            f.setVisible(true);
            
            /***************************************************************************/
        }
    }
    
    }
    
    }//GEN-LAST:event_jTableRMouseClicked

    private void btn_ajouter_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouter_roleActionPerformed
        addRole();
    }//GEN-LAST:event_btn_ajouter_roleActionPerformed

    private void btn_ajouter_filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouter_filmeActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<role> roles = new ArrayList<role>();
        for (int i = 0; i < model.getRowCount(); i++){
            roles.add(new role(String.valueOf(model.getValueAt(i, 0)),
                    String.valueOf(model.getValueAt(i, 1)),
                    String.valueOf(model.getValueAt(i, 2)))
            );
        }
        Film nvFilme = new Film(tf_titre_film.getText(),
                tf_genre_film.getText(),tf_pays_film.getText(),
                Integer.valueOf(tf_annee_film.getText()),
                Integer.valueOf(jComboBox1.getSelectedItem().toString()),
                roles, ta_resume_film.getText()
        );
        DefaultTableModel tblModel = (DefaultTableModel) jTableR.getModel();
        Object data[]  = {nvFilme.getTitre(),nvFilme.getGenre(), nvFilme.getPays(),nvFilme.getAnnee(),nvFilme.getMes(),nvFilme.getRoles(), nvFilme.getResume(),new JButton("show")};
        tblModel.addRow(data);
        JOptionPane.showMessageDialog(this,nvFilme.getTitre() + " a été ajouté avec succès" , "Succès", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_ajouter_filmeActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        readFilmFile(filename);
        try{
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            textArea.read(br, null);
            textArea.setCaretPosition(0);
            br.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        /************************/
        pHome.setVisible(false);
        pShow.setVisible(true);
        pCode.setVisible(false);
        pAdd.setVisible(false);
        pAbout.setVisible(false);
        homePanel.setVisible(false);
        xmlPanel.setVisible(false);
        tabPanel.setVisible(true);
        addPanel.setVisible(false);
        aboutPanel.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String cari = jTextField1.getText();
        TableRowSorter tr = new TableRowSorter(jTableR.getModel());
        jTableR.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(cari));
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
            try {
            Element FILMS = new Element("FILMS");
            Document doc = new Document(FILMS);
            DefaultTableModel model = (DefaultTableModel) jTableR.getModel();
            for(int i = 0; i< model.getRowCount(); i++){
                Element FILM = new Element("FILM");
                FILM.setAttribute(new Attribute("Annee",model.getValueAt(i, 3).toString()));
                FILM.addContent(new Element("TITRE").setText(model.getValueAt(i, 0).toString()));
                FILM.addContent(new Element("GENRE").setText(model.getValueAt(i, 1).toString()));
                FILM.addContent(new Element("PAYS").setText(model.getValueAt(i, 3).toString()));
                FILM.addContent(new Element("MES").setText(model.getValueAt(i, 4).toString()));
                Element ROLES = new Element("ROLES");
                ArrayList<role> r = (ArrayList<role>) model.getValueAt(i,5);
                for(int j = 0; j<r.size(); j++){
                    Element ROLE = new Element("ROLE");
                    ROLE.addContent(new Element("PRENOM").setText(r.get(j).getPrenom()));
                    ROLE.addContent(new Element("NOM").setText(r.get(j).getNom()));
                    ROLE.addContent(new Element("INTITULE").setText(r.get(j).getIntitule()));
                    ROLES.addContent(ROLE);
                }
                FILM.addContent(ROLES);
                if(model.getValueAt(i, 6) != null)
                    FILM.addContent(new Element("RESUME").setText(model.getValueAt(i, 6).toString()));
                else
                    FILM.addContent(new Element("RESUME").setText(""));
 
                doc.getRootElement().addContent(FILM);

            }
            
            for(int i = 0; i< artistes.size(); i++){
                Element ARTISTE = new Element("ARTISTE");
                ARTISTE.setAttribute(new Attribute("id",String.valueOf(artistes.get(i).getId())));
                ARTISTE.addContent(new Element("ACTNOM").setText(artistes.get(i).getNom()));
                ARTISTE.addContent(new Element("ACTPNOM").setText(artistes.get(i).getPrenom()));
                ARTISTE.addContent(new Element("ANNEENAISS").setText(artistes.get(i).getAnneeNaissance()));
                doc.getRootElement().addContent(ARTISTE);
            }
            XMLOutputter xmlOutput = new XMLOutputter();
            xmlOutput.setFormat(Format.getPrettyFormat());
            JFileChooser fc = new JFileChooser();
            fc.setDialogType(JFileChooser.SAVE_DIALOG);
            fc.setSelectedFile(new File("myFilm.xml"));
            fc.setFileFilter(new FileNameExtensionFilter("xml file", "xml"));
            if(fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            FileWriter fw = new FileWriter(f);
            xmlOutput.output(doc, fw);
            }
            } catch (IOException ex) {
            Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_topPanelMouseDragged

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
                showArtistes();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        clearForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnShowT;
    private javax.swing.JButton btnXML;
    private javax.swing.JButton btn_ajouter_filme;
    private javax.swing.JButton btn_ajouter_role;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private RSyntaxTextArea textArea;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableR;
    private ArrayList<Artiste> artistes;
    private int mouseX, mouseY;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel pAbout;
    private javax.swing.JPanel pAdd;
    private javax.swing.JPanel pCode;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pShow;
    private javax.swing.JTextArea ta_resume_film;
    private javax.swing.JPanel tabPanel;
    private javax.swing.JTextField tf_annee_film;
    private javax.swing.JTextField tf_genre_film;
    private javax.swing.JTextField tf_intitule_role;
    private javax.swing.JTextField tf_nom_role;
    private javax.swing.JTextField tf_pays_film;
    private javax.swing.JTextField tf_prenom_role;
    private javax.swing.JTextField tf_titre_film;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel xmlPanel;
    // End of variables declaration//GEN-END:variables

    private void showArtistes() {
        JTable mytable = new JTable();
                mytable.setBackground(Color.WHITE);
                mytable.setOpaque(true);
                
                mytable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Id", "Nom", "Prénom", "Annee de naissance"
                    }
                ) {
                    Class[] types = new Class [] {
                        java.lang.Integer.class,java.lang.String.class, java.lang.String.class, java.lang.Integer.class
                    };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            mytable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
            mytable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
            DefaultTableModel mdl = (DefaultTableModel) mytable.getModel();
                    for (int i = 0; i < artistes.size(); i++){
                        Artiste a = artistes.get(i);
                        Object data[]  = {a.getId(), a.getNom(), a.getPrenom(), a.getAnneeNaissance()};
                        mdl.addRow(data);
                    }
            JScrollPane scrollPane= new  JScrollPane(mytable);
            scrollPane.setBackground(Color.WHITE);
            scrollPane.setOpaque(true);
            JFrame f = new JFrame();
            f.getContentPane().add(scrollPane,BorderLayout.CENTER);
            f.setSize(400,300);
            f.setBackground(Color.WHITE);
            f.setTitle("Artistes");
            f.setVisible(true);
    }

    private void addRole() {
        role r = new role(tf_nom_role.getText(),tf_prenom_role.getText(),tf_intitule_role.getText());
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        Object data[]  = {r.getNom(),r.getPrenom(), r.getIntitule()};
        tblModel.addRow(data);
    }

    private void allWhite() {
        btnHome.setBackground(Color.WHITE);
        btnAdd.setBackground(Color.WHITE);
        btnShowT.setBackground(Color.WHITE);
        btnXML.setBackground(Color.WHITE);
        btnXML.setBackground(Color.WHITE);
    }
}
